version: '3.8'

services:
  bot:
    build: .
    container_name: auto_gift_bot
    volumes:
      - ./logs:/app/logs
      - ./database.db:/app/database.db
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres_data: 